CREATE INDEX CONCURRENTLY IDX_MEMBERSERVICE_ID ON MEMBERSERVICES USING btree(MEMBERSERVICE_ID);
CREATE INDEX CONCURRENTLY IDX_MEMEBERID ON MEMBERSERVICES USING btree(MEMBERID);
CREATE INDEX CONCURRENTLY IDX_RELATED_SERVICE_ID ON MEMBERSERVICES USING btree(RELATED_SERVICE_ID);
